### PR TITLE
Add RRULE parsing

### PR DESCRIPTION
**Pull request by ericdude4**
From the ICalendar spec: https://icalendar.org/iCalendar-RFC-5545/3-3-10-recurrence-rule.html

### CODE REVIEW

**Comment by lpil** [comment]
Is this ready to review?

**Comment by ericdude4** [comment]
I thought it was ready before, but then I added some more features 😛 

Let me integrate the new features into my application, then I will let you know when I think it's ready.

**Comment by ericdude4** [comment]
@lpil I am happy with this pull request now. Please review when you have some time :)

**Review by lpil — COMMENTED** [review]
The code looks good!

I was wondering about the Recurrence module. It seems that a hostile actor could submit an ical file with a frequent recurrance with an end date many years in the future, resulting in a vast amount of memory being used which would cause the application to crash.

Instead we could use the Stream module so that the memory usage is safe and constant, and it's indicated to the user that this may be a very large sequence.

**Comment by ericdude4** [comment]
Thank you for the feedback! I share your concerns. I will make these adjustments and let you know when they are ready.

**Comment by lpil** [comment]
Thank you!

**Comment by ericdude4** [comment]
@lpil Would you mind if I open this as a new PR so it's eligible for Hacktoberfest? If not, I get it :)

**Comment by lpil** [comment]
Hey nice idea. Go for it!

**Pull request closed without merging**
